export class ProduitImmobilierDTO {



    public static fromJson(json: object): ProduitImmobilierDTO {
        return new ProduitImmobilierDTO(
            json['id'],
            json['type'],
            json['telephone'],
            json['description'],
            json['nbrLots'],
            json['isParking'],
            json['isLift'],
            json['dpe'],
            json['nbrPiece'],
            json['nbrChambre'],
            json['chargesCoprop'],
            json['taxeFonciaire'],
            json['dateConstruction'],
            json['adresse'],
            json['codePostal'],
            json['ville'],
            json['prix'],
            json['surface'],
            json['surfaceBalcon'],
            json['surfaceTerrasse'],
            json['surfaceVerandas'],
            json['surfaceSousSol'],
            json['surfaceCave'],
            json['surfaceLogias'],
            json['autreSurfaceAnnexe'],
            json['loyerMaximum'],
            json['reductionImpots6ans'],
            json['reductionImpots9ans'],
            json['reductionImpots12ans'],
            json['collectionSize']);
    }
    constructor(
        public id: number,
        public type: string,
        public telephone: string,
        public description: string,
        public nbrLots: number,
        public isParking: number,
        public isLift: number,
        public dpe: string,
        public nbrPiece: number,
        public nbrChambre: number,
        public chargesCoprop: number,
        public taxeFonciaire: string,
        public dateConstruction: number,
        public adresse: string,
        public codePostal: string,
        public ville: string,
        public prix: number,
        public surface: number,
        public surfaceBalcon: number,
        public surfaceTerrasse: number,
        public surfaceVerandas: number,
        public surfaceSousSol: number,
        public surfaceCave: number,
        public surfaceLogias: number,
        public autreSurfaceAnnexe: number,
        public loyerMaximum: number,
        public reductionImpots6ans: number,
        public reductionImpots9ans: number,
        public reductionImpots12ans: number,
        public collectionSize: number) {
    }
}
